server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: jh
    password: jh
    #connection pool설정
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: jhpool
      
#mvc패턴으로 jsp페이지 연결하기
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
#jpa환경설정하기
  jpa:
    generate-ddl: true
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle9iDialect
    hibernate: 
      ddl-auto: update
      use-new-id-generator-mappings: true

#파일 업로드 처리  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB


mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml